package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/go-webauthn/webauthn/protocol"
	"github.com/tuoitrevohoc/gofw/backend/gen/go/ent"
	"github.com/tuoitrevohoc/gofw/backend/gen/go/ent/user"
	graphql1 "github.com/tuoitrevohoc/gofw/backend/gen/go/graphql"
	"github.com/tuoitrevohoc/gofw/backend/gen/go/graphql/model"
	"golang.org/x/crypto/bcrypt"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.SignUpInput) (*ent.User, error) {
	hasUser, err := r.client.User.Query().Where(
		user.Email(input.Email),
	).Exist(ctx)

	if err != nil {
		return nil, err
	}

	if hasUser {
		return nil, fmt.Errorf("user already exists")
	}

	encryptedPassword, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}

	user, err := r.client.User.Create().SetEmail(input.Email).SetPassword(string(encryptedPassword)).SetFinishedRegistration(true).Save(ctx)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.SignInInput) (*ent.User, error) {
	user, err := r.client.User.Query().Where(user.Email(input.Email)).Only(ctx)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// BeginAuthnRegistration is the resolver for the beginAuthnRegistration field.
func (r *mutationResolver) BeginAuthnRegistration(ctx context.Context, email string) (*model.AuthnRegistrationResponse, error) {
	credientialCreation, err := r.authenticator.BeginRegistration(ctx, email)

	if err != nil {
		return nil, fmt.Errorf("fail to begin passkey registration")
	}

	// convert credential to json
	json, err := json.Marshal(credientialCreation)
	if err != nil {
		return nil, fmt.Errorf("fail to create credential creation json")
	}

	return &model.AuthnRegistrationResponse{
		CredentialCreation: string(json),
	}, nil
}

// FinishAuthnRegistration is the resolver for the finishAuthnRegistration field.
func (r *mutationResolver) FinishAuthnRegistration(ctx context.Context, email string, response string) (*ent.User, error) {
	parsedResponse, err := protocol.ParseCredentialCreationResponseBytes([]byte(response))

	if err != nil {
		return nil, fmt.Errorf("fail to parse credential creation response")
	}

	user, err := r.authenticator.FinishRegistration(ctx, email, parsedResponse)
	if err != nil {
		return nil, fmt.Errorf("fail to finish passkey registration")
	}

	return user, nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
